Repository go-vela/types, pull requests merged in 2019-11, with the labels that each got.

#4 Add badges with coveralls
  .github/README.md
  .github/workflows/test.yml
Labels: enhancement

#5 Use goveralls to report test coverage to coveralls
  .github/workflows/test.yml
Labels: enhancement

#6 Fix bug with login
  library/login.go
Labels: bug

#9 Add tests and docs for Library setters
  library/build.go
  library/build_test.go
  library/log.go
  library/log_test.go
  library/login.go
  library/login_test.go
  library/repo.go
  library/repo_test.go
  library/secret.go
  library/secret_test.go
  library/service.go
  library/service_test.go
  library/step.go
  library/step_test.go
  library/user.go
  library/user_test.go
Labels: enhancement

#8 feat(disallow commands): add new parameter to secrets for injection
  database/secret.go
  database/secret_test.go
  library/secret.go
  library/secret_test.go
Labels: enhancement

#10 Adopt official mattn/goveralls integration
  .github/workflows/test.yml
Labels: enhancement

#12 Use buildkite/yaml to enable anchors in stages
  go.mod
  go.sum
  yaml/build_test.go
  yaml/stage.go
  yaml/stage_test.go
  yaml/testdata/build_anchor_stage.yml
  yaml/testdata/build_anchor_step.yml
Labels: bug

#13 Create Sanitize() to clean container ID field
  pipeline/container.go
  pipeline/container_test.go
Labels: bug

#14 test(secret): add tests using AllowCommand field
  library/secret.go
  library/secret_test.go
Labels: enhancement

#15 Add logic for webhook transaction log
  constants/table.go
  database/hook.go
  database/hook_test.go
  library/hook.go
  library/hook_test.go
Labels: feature

#16 Add disclaimer
  .github/README.md
Labels: enhancement

#17 Add the worker struct for routing to workers
  constants/queue.go
  pipeline/build.go
  pipeline/build_test.go
  pipeline/worker.go
  pipeline/worker_test.go
  yaml/build.go
  yaml/build_test.go
  yaml/testdata/build.yml
  yaml/worker.go
  yaml/worker_test.go
Labels: feature

#20 Add YAML pull tag to service configuration
  pipeline/worker_test.go
  yaml/service.go
Labels: feature

#21 Cleanup unused test
  library/secret_test.go
Labels: enhancement

#23 Add Number field to Hook struct
  database/hook.go
  database/hook_test.go
  database/service_test.go
  database/step_test.go
  library/hook.go
  library/hook_test.go
Labels: enhancement
