Repository go-vela/types, pull requests merged in 2020-04, with the labels that each got.

#43 feat(library): add AppendData() for Log
  library/log.go
  library/log_test.go
Labels: feature

#45 fix(yaml): create done channel for stages
  yaml/stage.go
  yaml/stage_test.go
Labels: bug

#44 feat(pipeline): add yaml tags for structs
  pipeline/build.go
  pipeline/container.go
  pipeline/metadata.go
  pipeline/port.go
  pipeline/ruleset.go
  pipeline/secret.go
  pipeline/stage.go
  pipeline/ulimit.go
  pipeline/volume.go
  pipeline/worker.go
Labels: feature

#46 feat: add masked value when sanitizing secrets
  constants/secret.go
  go.mod
  go.sum
  library/secret.go
  library/secret_test.go
Labels: feature

#47 feat: add comment support for ruleset
  constants/event.go
  database/repo.go
  database/repo_test.go
  library/repo.go
  library/repo_test.go
  library/secret.go
  library/secret_test.go
  pipeline/ruleset.go
  pipeline/ruleset_test.go
  yaml/ruleset.go
  yaml/ruleset_test.go
  yaml/testdata/ruleset_simple.yml
Labels: feature

#49 feat(service): add worker information
  database/service.go
  database/service_test.go
  library/service.go
  library/service_test.go
Labels: feature

#50 feat(constants): add pipeline types
  constants/limit.go
  constants/pipeline.go
Labels: feature

#53 feat(library): add ToString helper function
  go.mod
  go.sum
  library/string.go
  library/string_test.go
Labels: feature

#54 feat(library): add Environment() functions
  library/build.go
  library/build_test.go
  library/repo.go
  library/repo_test.go
  library/service.go
  library/service_test.go
  library/step.go
  library/step_test.go
  library/user.go
  library/user_test.go
Labels: feature

#55 test(library): refactor for table tests
  library/build_test.go
  library/context_test.go
  library/executor_test.go
  library/hook_test.go
  library/log_test.go
  library/login_test.go
  library/repo_test.go
  library/secret_test.go
  library/service_test.go
  library/step_test.go
  library/string_test.go
  library/user_test.go
Labels: enhancement

#56 test(database): refactor for table tests
  database/build_test.go
  database/context_test.go
  database/hook_test.go
  database/log_test.go
  database/repo_test.go
  database/secret_test.go
  database/service_test.go
  database/step_test.go
  database/user_test.go
Labels: enhancement

#57 feat(library): add deployment type
  library/deployment.go
  library/deployment_test.go
Labels: feature

#58 test(raw): refactor for table tests
  raw/map_test.go
  raw/slice_test.go
Labels: enhancement

#59 fix: revert match functions for status
  pipeline/ruleset.go
  pipeline/ruleset_test.go
Labels: bug

#60 test(pipeline): refactor for table tests
  pipeline/build_test.go
  pipeline/container.go
  pipeline/container_test.go
  pipeline/context_test.go
  pipeline/ruleset.go
  pipeline/stage_test.go
  pipeline/worker_test.go
Labels: enhancement

#61 feat(library): add build deployment env vars
  library/build.go
  library/build_test.go
Labels: feature

#62 feat(ruleset): support deployment target
  pipeline/ruleset.go
  pipeline/ruleset_test.go
  yaml/ruleset.go
  yaml/ruleset_test.go
Labels: feature
