Repository go-vela/types, pull requests merged in 2021-12, with the labels that each got.

#220 feat(secrets): adding logging mask constant
  constants/secret.go
Labels: feature

#215 feat(stage): add environment field
  pipeline/stage.go
  pipeline/stage_test.go
  yaml/stage.go
  yaml/stage_test.go
  yaml/testdata/stage.yml
Labels: feature

#221 chore(deps): update go to 1.17
  .github/workflows/release.yml
  .github/workflows/reviewdog.yml
  .github/workflows/schema.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  go.mod
  version/metadata_test.go
  version/version_test.go
Labels: dependencies

#217 enhance(webhook): enable skipping builds during tag events
  webhook.go
  webhook_test.go
Labels: enhancement

#222 feat(library): add Duration() function to resources
  library/build.go
  library/build_test.go
  library/service.go
  library/service_test.go
  library/step.go
  library/step_test.go
Labels: feature

#218 feat(repo): Add Name History field to Repo type
  constants/event.go
  database/repo.go
  database/repo_test.go
  library/repo.go
  library/repo_test.go
Labels: feature
