Repository go-vela/types, pull requests merged in 2021-02, with the labels that each got.

#144 revert: library swap to goccy
  go.mod
  go.sum
  yaml/build.go
  yaml/build_test.go
  yaml/metadata_test.go
  yaml/ruleset_test.go
  yaml/secret.go
  yaml/secret_test.go
  yaml/service.go
  yaml/service_test.go
  yaml/stage.go
  yaml/stage_test.go
  yaml/step.go
  yaml/step_test.go
  yaml/template_test.go
  yaml/ulimit_test.go
  yaml/volume_test.go
Labels: bug

#151 feat: add MergeEnv() for resource environment variables
  pipeline/container.go
  pipeline/container_test.go
  yaml/secret.go
  yaml/secret_test.go
  yaml/service.go
  yaml/service_test.go
  yaml/step.go
  yaml/step_test.go
Labels: feature

#154 feat(database): add log Compress() and Decompress()
  constants/compress.go
  database/log.go
  database/log_test.go
  go.mod
  go.sum
Labels: feature

#156 enhance(database): support setting different compression level
  constants/compress.go
  constants/compression.go
  database/log.go
  database/log_test.go
Labels: enhancement
