Repository go-vela/types, pull requests merged in 2021-05, with the labels that each got.

#175 fix(comment): skip worker from evaluating comment for comment events
  library/repo.go
  pipeline/container.go
  pipeline/container_test.go
Labels: bug

#174 feat(database): use struct tags for custom types in gorm
  database/build.go
  database/secret.go
  database/user.go
  database/worker.go
Labels: feature

#176 feat(repo): add a counter field
  database/repo.go
  database/repo_test.go
  library/repo.go
  library/repo_test.go
Labels: feature

#177 fix: update the schema links to ref docs
  yaml/build.go
  yaml/metadata.go
  yaml/ruleset.go
  yaml/secret.go
  yaml/service.go
  yaml/stage.go
  yaml/step.go
  yaml/template.go
  yaml/ulimit.go
  yaml/volume.go
  yaml/worker.go
Labels: enhancement
