Repository go-vela/types, pull requests merged in 2021-01, with the labels that each got.

#127 feat(library): enable creating resources from container
  library/service.go
  library/service_test.go
  library/step.go
  library/step_test.go
Labels: feature

#129 feat(pipeline): add container substitute function
  go.mod
  go.sum
  pipeline/container.go
  pipeline/container_test.go
Labels: feature

#126 feat: add validation for secret block
  yaml/build.go
  yaml/secret.go
  yaml/secret_test.go
  yaml/service.go
  yaml/stage.go
  yaml/step.go
  yaml/testdata/secret/validate/no_name.yml
  yaml/testdata/secret/validate/org.yml
  yaml/testdata/secret/validate/org_bad_engine.yml
  yaml/testdata/secret/validate/org_bad_key.yml
  yaml/testdata/secret/validate/plugin.yml
  yaml/testdata/secret/validate/plugin_bad_image.yml
  yaml/testdata/secret/validate/plugin_bad_name.yml
  yaml/testdata/secret/validate/repo.yml
  yaml/testdata/secret/validate/repo_bad_engine.yml
  yaml/testdata/secret/validate/repo_bad_key.yml
  yaml/testdata/secret/validate/shared.yml
  yaml/testdata/secret/validate/shared_bad_engine.yml
  yaml/testdata/secret/validate/shared_bad_key.yml
Labels: feature

#87 feat(token): add refresh token info
  constants/token.go
  database/user.go
  database/user_test.go
  library/login.go
  library/login_test.go
  library/user.go
  library/user_test.go
  metadata.go
Labels: enhancement, feature

#135 feat: add workspace constants for services and steps
  constants/workspace.go
Labels: feature

#140 fix(schema): fix two bugs
  cmd/schema/main.go
Labels: bug
