Repository go-vela/types, pull requests merged in 2022-01, with the labels that each got.

#219 feat(repo): add build limit field
  constants/limit.go
  database/repo.go
  database/repo_test.go
  library/repo.go
  library/repo_test.go
Labels: feature

#226 feat(library): add ServiceFromBuildContainer()
  library/service.go
  library/service_test.go
  library/step.go
  library/step_test.go
Labels: feature

#227 enhance(library): update Duration() return values
  library/build.go
  library/build_test.go
  library/service.go
  library/service_test.go
  library/step.go
  library/step_test.go
Labels: enhancement

#210 fix(secret)!: remove implicit repo secrets and clean up secrets testing
  constants/secret.go
  pipeline/secret.go
  pipeline/secret_test.go
Labels: bug
