Repository go-vela/types, pull requests merged in 2022-03, with the labels that each got.

#230 fix(secret)!: remove implicit repo secrets and clean up secrets testing
  constants/secret.go
  pipeline/secret.go
  pipeline/secret_test.go
Labels: bug

#234 chore: Update golangci configuration
  .golangci.yml
  constants/badge.go
  database/build.go
  database/log_test.go
  database/repo.go
  database/repo_test.go
  database/secret_test.go
  database/service.go
  database/step.go
  database/user_test.go
  database/worker.go
  library/build.go
  library/hook.go
  library/log.go
  library/log_test.go
  library/login.go
  library/login_test.go
  library/secret_test.go
  library/service.go
  library/step.go
  pipeline/container.go
  pipeline/secret.go
  pipeline/secret_test.go
  raw/map.go
  raw/map_test.go
  webhook.go
  yaml/build.go
  yaml/metadata.go
  yaml/ruleset.go
  yaml/secret.go
  yaml/service.go
  yaml/stage.go
  yaml/stage_test.go
  yaml/step.go
  yaml/template.go
  yaml/ulimit.go
  yaml/volume.go
  yaml/worker.go
Labels: enhancement

#237 feat: support stages with templates
  pipeline/metadata.go
  yaml/metadata.go
  yaml/template.go
Labels: feature

#240 fix(metadata): moving metadata unmarshaler override to build
  yaml/build.go
  yaml/build_test.go
  yaml/metadata.go
  yaml/metadata_test.go
  yaml/testdata/build.yml
  yaml/testdata/build_empty_env.yml
Labels: bug

#223 feat: add database and library pipeline type
  constants/table.go
  database/build.go
  database/build_test.go
  database/pipeline.go
  database/pipeline_test.go
  library/build.go
  library/build_test.go
  library/pipeline.go
  library/pipeline_test.go
  yaml/build.go
  yaml/build_test.go
  yaml/testdata/build.yml
Labels: feature
